---
title: "Deliverable 1"
date: "1.11.23"
output:
  html_document:
    df_print: paged
---
```{r, message=FALSE}
#loading packages
library(ggplot2)
library(tidyverse)
library(ggthemes)
```

```{r}
#loading in data from github
location='https://github.com/543DataVisual/Deliverable1/raw/main/' 
file='copy_tractassignments.csv'
link=paste0(location,file)

mydata=read.csv(link)
```

```{r, message=FALSE}
#creating elements to be included on visual
message = "*Only 1 tract contains highest quantity
            of non-english speakers in it*"
mn = mean(mydata$total_non_english,na.rm = T)
annMean = paste0('Mean:',round(mn))
labels = labs(x = "Non-English Speakers", y = "Counts of Tracts", title = "Total Non-English Speakers", 
               subtitle = "in Each Tract in The City of Bellevue, Washington USA")

gginfo = mydata %>% ggplot(aes(x = total_non_english)) +
  geom_histogram(fill = "#a3b18a", color = "white") + 
  geom_vline(aes(xintercept=mean(total_non_english))) +
  annotate(geom = 'text',color='red',
             label=annMean,
              y = 4,
              x= mn+100,
              angle=90) +
  annotate(geom = 'text', color="#a3b18a",
           label=message,
           y=3,
           x=mn+1400,
           angle=0)
#creating visual
graph = 
  gginfo + 
  labels + 
  theme_few()

graph
```

